pipeline {
    agent any
    stages {
        stage('Installing dependencies') {
            steps {                 
                sh '''
                    echo 'Start installing dependencies'
                    echo 'pip version'
                    pip3 install --upgrade setuptools
                    pip3 install -r "api_gateway/requirements.txt"
                    '''
             }
        }         
        stage('Running test cases') {
            steps {                 
                sh '''
                   echo 'Start running test cases'
                    python3 "api_gateway/app/tests/test.py"
                  '''
             }
        }
        stage('Building Docker image') {
            steps {
            sh '''
                cd "api_gateway"
                sudo apt install docker.io
                sudo systemctl start docker
                sudo systemctl enable docker        
                sudo docker build -t api_gateway .
            '''    
            }
        }
        stage('Pushing to Docker hub') {
            steps {
            sh '''
                sudo docker login --username=juhideshkar30 --password=qwertyuiop12345
                sudo docker tag api_gateway juhideshkar30/api_gateway                
                sudo docker push juhideshkar30/api_gateway
            '''    
            }
        }
        stage('SSH call to Kubernetes master') {
            steps {
            sh '''
                cd "api_gateway" 
                chmod 400 nirvana.pem
                ssh -o StrictHostKeyChecking=no -i nirvana.pem ubuntu@149.165.169.31 uptime
                ssh -i nirvana.pem ubuntu@149.165.169.31 " rm -rf Nirvana &&
                git clone https://github.com/airavata-courses/Nirvana.git &&
                cd Nirvana &&
                git pull &&
                git checkout Kubernetes_files &&
                cd yaml_files/api_gateway && 
                export KUBECONFIG=/etc/kubernetes/admin.conf
                kubectl delete service api-gateway &&
                kubectl delete deployment api-gateway &&
                kubectl apply -f config.yaml"
            '''    
            }
        }
    }
}
