apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5000
    port: 5000
    nodePort: 30010
 selector:
  app: python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: python
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: api-gateway-microservice
        imagePullPolicy: Always
        image: juhideshkar30/api_gateway
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 5000
