apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5000
    port: 5000
    nodePort: 30010
 selector:
  app: flask-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: flask-ms
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-ms
    spec:
      containers:
      - name: api-gateway-microservice
        imagePullPolicy: Always
        image: juhideshkar30/api_gateway
        ports:
        - containerPort: 5000
