apiVersion: v1
kind: Service
metadata:
  name: data-analysis-visualization
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5003
    port: 5003
    nodePort: 30004
 selector:
  app: python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-analysis-visualization
spec:
  selector:
    matchLabels:
      app: python
  replicas: 3
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: data-analysis-microservice
        imagePullPolicy: Always
        image: juhideshkar30/analysis_visualisation
        ports:
        - containerPort: 5003
