pipeline {
    agent any
    stages {
        stage('Installing dependencies') {
            steps {                 
                sh '''
                    echo 'Start installing dependencies'
                    echo 'pip version'
                    python3 -m pip --version
                    python3 -m pip install --upgrade setuptools
                    python3 -m pip install -r "microservices/Microservice_Model Execution/requirements.txt"
                    '''
             }
        }         
        stage('Running test cases') {
            steps {                 
                sh '''
                   echo 'Start running test cases'
                    python3 "microservices/Microservice_Model Execution/app/tests/test.py"
                  '''
             }
        }
        stage('Building Docker image') {
            steps {
            sh '''
                cd "microservices/Microservice_Model Execution"
                sudo apt --assume-yes install docker.io
                sudo systemctl start docker
                sudo systemctl enable docker        
                sudo docker build -t modelexecution-service .
            '''    
            }
        }
        stage('Pushing to Docker hub') {
            steps {
            sh '''
                sudo docker login --username=juhideshkar30 --password=qwertyuiop12345
                sudo docker tag modelexecution-service juhideshkar30/model_execution_service                
                sudo docker push juhideshkar30/model_execution_service  
            '''    
            }
        }
    }
}
