pipeline {
    agent any
    stages {
        stage('Installing dependencies') {
            steps {                 
                sh '''
                    echo 'Start installing dependencies'
                    echo 'pip version'
                    pip3 install --upgrade setuptools
                    pip3 install -r "microservices/Microservice_Model Execution/requirements.txt"
                    '''
             }
        }         
        stage('Running test cases') {
            steps {                 
                sh '''
                   echo 'Start running test cases'
                    python3 "microservices/Microservice_Model Execution/app/tests/test.py"
                  '''
             }
        }
        stage('Building Docker image') {
            steps {
            sh '''
                cd "microservices/Microservice_Model Execution"
                sudo -S apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker        
                sudo docker build -t modelexecution-service .
            '''    
            }
        }
        stage('Pushing to Docker hub') {
            steps {
            sh '''
                sudo docker login --username=juhideshkar30 --password=qwertyuiop12345
                sudo docker tag modelexecution-service juhideshkar30/model_execution_service                
                sudo docker push juhideshkar30/model_execution_service  
            '''    
            }
        }
        stage('SSH call to Kubernetes master') {
            steps {
            sh '''
                cd "microservices/Microservice_Model Execution" 
                chmod 400 nirvana.pem
                ssh -o StrictHostKeyChecking=no -i nirvana.pem ubuntu@149.165.169.122 uptime
                ssh -i nirvana.pem ubuntu@149.165.169.122 " rm -rf Nirvana &&
                git clone https://github.com/airavata-courses/Nirvana.git &&
                cd Nirvana &&
                git pull &&
                git checkout Kubernetes_files &&
                cd yaml_files/microservice_model_execution && 
                sudo -s export KUBECONFIG=/etc/kubernetes/admin.conf &&
                kubectl delete service model-execution &&
                kubectl delete deployment model-execution &&
                kubectl apply -f config.yaml"
            '''    
            }
        }
    }
}
