apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper1
  template:
    metadata:
      labels:
        app: zookeeper1
    spec:
      containers:
      - name: zookeeper1
        image: thertion12/zookeeper
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
