pipeline {
    agent any
    stages {
        stage('Installing dependencies') {
            steps {                 
                sh '''
                    sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
                    sudo -S apt install -y nodejs
                    curl -L https://npmjs.org/install.sh | sudo sh
                    '''
             }
        }         
        
        stage('Building Docker image') {
            steps {
            sh '''
                cd "ReactFrontEnd/nirvana-frontend"
                npm install
                npm run build
                sudo -S apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker        
                sudo docker build -t frontend-service .
            '''    
            }
        }
        stage('Pushing to Docker hub') {
            steps {
            sh '''
                sudo docker login --username=juhideshkar30 --password=qwertyuiop12345
                sudo docker tag frontend-service juhideshkar30/frontend                
                sudo docker push juhideshkar30/frontend
            '''    
            }
        }
        stage('SSH call to Kubernetes master') {
            steps {
            sh '''
                cd "ReactFrontEnd/nirvana-frontend" 
                chmod 400 nirvana.pem
                ssh -o StrictHostKeyChecking=no -i nirvana.pem ubuntu@149.165.169.122 uptime
                ssh -i nirvana.pem ubuntu@149.165.169.122 " rm -rf Nirvana &&
                git clone https://github.com/airavata-courses/Nirvana.git &&
                cd Nirvana &&
                git pull &&
                git checkout Kubernetes_files &&
                cd yaml_files/frontend && 
                sudo -s export KUBECONFIG=/etc/kubernetes/admin.conf &&
                
                kubectl apply -f config.yaml"
            '''    
            }
        }
    }
}
