pipeline {
    agent any
    stages {
        stage('Installing dependencies') {
            steps {                 
                sh '''
                    sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
                    sudo apt --assume-yes install nodejs
                    curl -L https://npmjs.org/install.sh | sudo sh
                    '''
             }
        }         
        
        stage('Building Docker image') {
            steps {
            sh '''
                cd "ReactFrontEnd/nirvana-frontend"
                npm install
                npm run build
                sudo apt --assume-yes install docker.io
                sudo systemctl start docker
                sudo systemctl enable docker        
                sudo docker build -t frontend-service .
            '''    
            }
        }
        stage('Pushing to Docker hub') {
            steps {
            sh '''
                sudo docker login --username=juhideshkar30 --password=qwertyuiop12345
                sudo docker tag frontend-service juhideshkar30/frontend                
                sudo docker push juhideshkar30/frontend
            '''    
            }
        }
        stage('SSH call to Kubernetes master') {
            steps {
            sh '''
                cd "ReactFrontEnd/nirvana-frontend" 
                chmod 400 nirvana.pem
                ssh -o StrictHostKeyChecking=no -i nirvana.pem ubuntu@149.165.169.31 uptime
                ssh -i nirvana.pem ubuntu@149.165.169.31 " rm -rf Nirvana &&
                git clone https://github.com/airavata-courses/Nirvana.git &&
                cd Nirvana &&
                git pull &&
                git checkout React-UI &&
                cd yaml_files/frontend && 
                export KUBECONFIG=/etc/kubernetes/admin.conf
                kubectl apply -f config.yaml"
            '''    
            }
        }
    }
}
