apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5003
    port: 5003
    nodePort: 30009
 selector:
  app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: react-frontend
        imagePullPolicy: Always
        image: juhideshkar30/frontend
        ports:
        - containerPort: 9090
