apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
 type: LoadBalancer
 ports:
  - targetPort: 5000
    port: 5000
    nodePort: 9092
  - targetPort: 5001
    port: 5001
    nodePort: 2181
 selector:
  app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: juhideshkar30/kafka
        ports:
        - containerPort: 9092
      - name: kafka-manager
        imagePullPolicy: Always
        image: juhideshkar30/kafka-manager
        ports:
        - containerPort: 2181
