pipeline {
    agent any
    stages {
        stage('Installing dependencies') {
            steps {                 
                sh '''
                    echo 'Start installing dependencies'
                    echo 'pip version'
                    python3 -m pip --version
                    python3 -m pip install --upgrade setuptools
                    python3 -m pip install -r "microservices/Microservice_Data Retrieval/requirements.txt"
                    '''
             }
        }         
        stage('Running test cases') {
            steps {                 
                sh '''
                   echo 'Start running test cases'
                    python3 "microservices/Microservice_Data Retrieval/app/tests/test.py"
                  '''
             }
        }
        stage('Deploy') {
            steps {
            sh '''
                ssh -t remotehost "sudo ./binary"
                cd "microservices/Microservice_Data Retrieval"
                sudo apt-get remove docker docker-engine docker.io
                apt install docker.io
                systemctl start docker
                systemctl enable docker        
                docker build -t dataretrieval-service .
            '''    
            }
        }
    }
}
