node{
    checkout scm
    docker.withRegistry('https://registry.hub.docker.com', 'dockerHub'){
        def dockerimage = docker.build("juhideshkar30/data_retrieval")
        dockerimage.push()
    }
}


