pipeline {
    agent any
    stages {
        stage('Initialize')
        {
            steps{
                scripts{        
                    def dockerHome = tool 'Docker'
                    env.PATH = "${dockerHome}/bin:${env.PATH}"
                }
            }
        }
        stage('testing') {
            steps {                 
                sh '''
                   git checkout Microservice_DataRetrieval
                   cd "microservices/Microservice_Data Retrieval/Microservice_Data Retrieval"
                   docker build -t image_name .
                '''    
             }
        }
    }
}
