apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - env:
        - name: ZK_HOSTS
          value: 149.165.169.31:2181
        image: mzagar/kafka-manager-docker:1.3.3.4
        name: kafkamanager
        ports:
        - containerPort: 9000
      restartPolicy: Always
