apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-manager
  name: kafka-manager
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-manager
    spec:
      containers:
      - env:
        - name: ZK_HOSTS
          value: kafkaserver:2181
        image: mzagar/kafka-manager-docker:1.3.3.4
        name: kafkamanager
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
