apiVersion: v1
kind: Service
metadata:
  name: kafkaserver
spec:
  type: LoadBalancer
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
    nodePort: 30012
  - name: "9092"
    port: 9092
    targetPort: 9092
    nodePort: 30011
  selector:
    app: app
