apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - env:
        - name: ADVERTISED_HOST
          value: 149.165.169.31
        - name: ADVERTISED_PORT
          value: "9092"
        image: spotify/kafka:latest
        name: kafka
        ports:
        - containerPort: 2181
        - containerPort: 9092
      hostname: kafkaserver
      restartPolicy: Always
