apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kafkaserver
  name: kafkaserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: kafkaserver
    spec:
      containers:
      - env:
        - name: ADVERTISED_HOST
          value: kafkaserver
        - name: ADVERTISED_PORT
          value: "9092"
        image: spotify/kafka:latest
        name: kafka
        ports:
        - containerPort: 2181
        - containerPort: 9092
        resources: {}
      hostname: kafkaserver
      restartPolicy: Always
status: {}
