pipeline {
    agent any
    stages {
        stage('Installing dependencies') {
            steps {                 
                sh '''
       
                    sudo apt --assume-yes install maven
                    cd "microservices/Microservice_User Management"
                    mvn pre-clean
                    mvn compile
                    mvn package
                    
                    '''
             }
        }
        stage('Running test cases') {
            steps {                 
                sh '''
                   echo 'Start running test cases'
                   cd "microservices/Microservice_User Management"
                    mvn test
                  '''
             }
        }
        stage('Building Docker image') {
            steps {
            sh '''
                cd "microservices/Microservice_User Management"
                sudo apt --assume-yes install docker.io
                sudo systemctl start docker
                sudo systemctl enable docker        
                sudo docker build -t user-management-service .
                echo "Docker build successful"
            '''    
            }
        }
        stage('Pushing to Docker hub') {
            steps {
            sh '''
                sudo docker login --username=juhideshkar30 --password=qwertyuiop12345
                sudo docker tag user-management-service juhideshkar30/user_management_service                
                sudo docker push juhideshkar30/user_management_service
               '''    
            }
        }
         stage('SSH call to Kubernetes master') {
            steps {
            sh '''
                cd "microservices/Microservice_User Management" 
                chmod 400 nirvana.pem
                ssh -o StrictHostKeyChecking=no -i nirvana.pem ubuntu@149.165.169.31 uptime
                ssh -i nirvana.pem ubuntu@149.165.169.31 " rm -rf Nirvana &&
                git clone https://github.com/airavata-courses/Nirvana.git &&
                cd Nirvana &&
                git pull &&
                git checkout Kubernetes_files &&
                cd yaml_files/microservice_user_management && 
                export KUBECONFIG=/etc/kubernetes/admin.conf &&
                kubectl delete service user-management &&
                kubectl delete deployment user-management &&
                kubectl apply -f config.yaml"
            '''    
            }
        }
    }
}
