pipeline {
    agent any
    stages {
        stage('Installing dependencies') {
            steps {                 
                sh '''
                    echo 'Start installing dependencies'
                    pip3 install --upgrade setuptools
                    pip3 install -r "microservices/Microservice_DataAnalaysis and Visualization/requirements.txt"
                    '''
             }
        }         
        stage('Running test cases') {
            steps {                 
                sh '''
                   echo 'Start running test cases'
                    python3 "microservices/Microservice_DataAnalaysis and Visualization/app/tests/test.py"
                  '''
             }
        }
        stage('Building Docker image') {
            steps {
            sh '''
                cd "microservices/Microservice_DataAnalaysis and Visualization"
                sudo -S apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker        
                sudo docker build -t analysis-visualisation-service .
            '''    
            }
        }
        stage('Pushing to Docker hub') {
            steps {
            sh '''
                sudo docker login --username=juhideshkar30 --password=qwertyuiop12345
                sudo docker tag analysis-visualisation-service juhideshkar30/analysis_visualisation               
                sudo docker push juhideshkar30/analysis_visualisation 
            '''    
            }
        }
        stage('SSH call to Kubernetes master') {
            steps {
            sh '''
                cd "microservices/Microservice_DataAnalaysis and Visualization" 
                chmod 400 nirvana.pem
                ssh -o StrictHostKeyChecking=no -i nirvana.pem ubuntu@149.165.169.122 uptime
                ssh -i nirvana.pem ubuntu@149.165.169.122 " rm -rf Nirvana &&
                git clone https://github.com/airavata-courses/Nirvana.git &&
                cd Nirvana &&
                git pull &&
                git checkout Kubernetes_files &&
                cd yaml_files/microservice_data_analysis_and_visualization && 
                export KUBECONFIG=/etc/kubernetes/admin.conf
                kubectl delete service data-analysis-visualization &&
                kubectl delete deployment data-analysis-visualization &&
                kubectl apply -f config.yaml"
            '''    
            }
        }
    }
}
