apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
 type: LoadBalancer
 ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30008
 selector:
  app: java-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  selector:
    matchLabels:
      app: java-ms
  replicas: 5
  template:
    metadata:
      labels:
        app: java-ms
    spec:
      containers:
      - name: user-management-microservice
        imagePullPolicy: Always
        image: juhideshkar30/user_management_service
        ports:
        - containerPort: 5003